# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: workspace_test
          POSTGRES_USER: beaverthing
          POSTGRES_PASSWORD: beaverthing
    env:
      RAILS_ENV: test
      SELENIUM_HOST: browser
      SELENIUM_PORT: 4444
      RAILS_HOST: ruby
      RAILS_PORT: 3000
    steps:
      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: nodejs 
      - name: Start Selenium
        run: docker run -d -p 4444:4444 -p 5900:5900 -p 7900:7900 --name selenium selenium/standalone-firefox
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          ruby-version: 3.2.0
      # Add or replace database setup steps here
      - name: Set up database schema
        run: 
          bin/rails db:create
          bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake cucumber
      - name: Stop Selenium
        run: docker stop selenium
        if: always()
