# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: workspace_test
          POSTGRES_USER: beaverthing
          POSTGRES_PASSWORD: beaverthing
    env:
      RAILS_ENV: test
      #DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: nodejs 
      - name: Set up Chrome driver
        run: |
          LATEST=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          ruby-version: 3.2.0
      # Add or replace database setup steps here
      - name: Set up database schema
        run: 
          bundle install
          bin/rails db:create
          bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          bin/rake cucumber
